In [1]:
#Neuron with 3 inputs

inputs = [1,2,3]
weights = [0.2,0.8,-0.5]
bias=2

outputs=(inputs[0]*weights[0]+inputs[1]*weights[1]+inputs[2]*weights[2]+bias)
print(outputs)

2.3


In [2]:
#Neuron with 4 inputs

inputs = [1,2,3,2.5]
weights = [0.2,0.8,-0.5,1]
bias = 2

output=(inputs[0]*weights[0]+inputs[1]*weights[1]+inputs[2]*weights[2]+inputs[3]*weights[3]+bias)
print(output)

4.8


In [3]:
#Layer of Neurons

inputs=[1,2,3,2.5]

weights=[[0.2,0.8,-0.5,1],
         [0.5,-0.91,0.26,-0.5],
         [-0.26,-0.27,0.17,0.87]]

biases=[2,3,0.5]

weight1=weights[0]
weight2=weights[1]
weight3=weights[2]

outputs=(inputs[0]*weight1[0]+inputs[1]*weight1[1]+inputs[2]*weight1[2]+inputs[3]*weight1[3]+biases[0],
         inputs[0]*weight2[0]+inputs[1]*weight2[1]+inputs[2]*weight2[2]+inputs[3]*weight2[3]+biases[1],
         inputs[0]*weight3[0]+inputs[1]*weight3[1]+inputs[2]*weight3[2]+inputs[3]*weight3[3]+biases[2])
#Since inputs are same for the three neurons in a layer - it is the weights and biases that change

print(outputs)

(4.8, 1.21, 2.385)


In [4]:
#Layer of Neurons using Loops

inputs=[1,2,3,2.5]

weights=[[0.2,0.8,-0.5,1],
         [0.5,-0.91,0.26,-0.5],
         [-0.26,-0.27,0.17,0.87]]

biases=[2,3,0.5]

output_list=[]

for n_weights,n_bias in zip(weights,biases):
    n_output=0
    for n_input,weight in zip(inputs,n_weights):
        n_output+=n_input*weight
    n_output+=n_bias
    output_list.append(n_output)

print(output_list)

[4.8, 1.21, 2.385]


In [10]:
# inputs=[1,2,3,2.5]

# weights=[[0.2,0.8,-0.5,1],
#          [0.5,-0.91,0.26,-0.5],
#          [-0.26,-0.27,0.17,0.87]]

# biases=[2,3,0.5]

# print(list(zip(weights,biases)))

In [11]:
#print(list(zip(inputs,weights[0])))

In [12]:
#Neurons and Layers - Using Numpy

In [13]:
#Neuron with 3 inputs - Numpy

import numpy as np

inputs=[1,2,3]
weights=[0.2,0.8,-0.5]
bias = 2
outputs=np.dot(inputs,weights)+bias
print(outputs)

2.3


In [18]:
#Layer of neurons - Numpy

import numpy as np

inputs=[[1],[2],[3],[2.5]]

weights=[[0.2,0.8,-0.5,1],
         [0.5,-0.91,0.26,-0.5],
         [-0.26,-0.27,0.17,0.87]]

biases=[[2],[3],[0.5]]

outputs=np.dot(weights,inputs)+biases
print(outputs)
#Much more elegant than coding individually or even using loops

[[4.8  ]
 [1.21 ]
 [2.385]]


In [19]:
#Processing batches of inputs

import numpy as np

inputs=[[1,2,3,2.5],[2,5,-1,2],[-1.5,2.7,3.3,-0.8]]

weights=[[0.2,0.8,-0.5,1],
         [0.5,-0.91,0.26,-0.5],
         [-0.26,-0.27,0.17,0.87]]

biases=[2,3,0.5]

outputs=np.dot(inputs,np.array(weights).T)+biases
print(outputs)


[[ 4.8    1.21   2.385]
 [ 8.9   -1.81   0.2  ]
 [ 1.41   1.051  0.026]]


In [20]:
#Coding multiple layers and stacking them together

import numpy as np

inputs=[[1,2,3,2.5],[2,5,-1,2],[-1.5,2.7,3.3,-0.8]]

weights1=[[0.2,0.8,-0.5,1],
         [0.5,-0.91,0.26,-0.5],
         [-0.26,-0.27,0.17,0.87]]

biases1=[2,3,0.5]

weights2=[[0.1,-0.14,0.5],
          [-0.5,0.12,-0.33],
          [-0.44,0.73,-0.13]]

biases2=[-1,2,-0.5]

arr_inputs=np.array(inputs)
arr_weights1=np.array(weights1)
arr_biases1=np.array(biases1)
arr_weights2=np.array(weights2)
arr_biases2=np.array(biases2)

outputs1=np.dot(arr_inputs,arr_weights1.T)+arr_biases1
outputs2=np.dot(outputs1,arr_weights2.T)+arr_biases2
print(outputs2)



[[ 0.5031  -1.04185 -2.03875]
 [ 0.2434  -2.7332  -5.7633 ]
 [-0.99314  1.41254 -0.35655]]


In [12]:
import numpy as np
class Activation_ReLU:
    def forward(self,inputs):
        self.outputs=np.maximum(0,inputs)
        return self.outputs

In [13]:
inputs=[0,2,-1,3.3,-2.7,1.1,2.2,-100]
relu=Activation_ReLU()
print(relu.forward(inputs))

[0.  2.  0.  3.3 0.  1.1 2.2 0. ]


In [21]:
softmax_outputs = np.array([[0.7,0.1,0.2],
                             [0.1,0.5,0.4],
                             [0.02,0.9,0.08]])
class_targets = [0,1,1]

relevant_values = softmax_outputs[range(len(softmax_outputs)),class_targets]
neg_log= (-np.log(relevant_values))
average_loss=np.mean(neg_log)
print(average_loss)

0.38506088005216804


In [22]:
y_pred=np.array([[0.7,0.1,0.2],
                  [0.1,0.5,0.4],
                  [0.02,0.9,0.08]])

y_true=np.array([[1,0,0],
                  [0,1,0],
                  [0,1,0]])

relevant_values=np.sum(y_pred*y_true,axis=1)
neg_loss= (-np.log(relevant_values))
average_loss=np.mean(neg_loss)
print(average_loss)

0.38506088005216804


In [44]:
# Coding backpropagation for a single neuron

import numpy as np

inputs=np.array([1.0,-2.0,3.0])
weights=np.array([-3.0,-1.0,2.0])
bias=1
target_output=0.0
learning_rate=0.001

def ReLU(x):
    return np.maximum(0,x)

def derivative_relu(x):
    if x>0:
        return 1
    else:
        return 0

for i in range(200):
    
    linear_output=np.dot(inputs,weights)+bias
    output=ReLU(linear_output)
    loss=(output-target_output)**2

    dloss_drelu=2*(output-target_output)
    drelu_dlinear=derivative_relu(linear_output)
    dlinear_dmul=1
    dmul_dweights=inputs
    
    dloss_dweights=dloss_drelu*drelu_dlinear*dlinear_dmul*dmul_dweights
    dloss_dbias=dloss_drelu*drelu_dlinear*1

    weights-=learning_rate*dloss_dweights
    bias-=learning_rate*dloss_dbias

    if i%10==0:
        print(f"Iteration : {i+1}, Loss : {loss}")

print("Final weights : ",weights)
print("Final bias : ",bias)
    

Iteration : 1, Loss : 36.0
Iteration : 11, Loss : 19.576596345362915
Iteration : 21, Loss : 10.645642346368787
Iteration : 31, Loss : 5.789040084776769
Iteration : 41, Loss : 3.1480472490777887
Iteration : 51, Loss : 1.7118902853146072
Iteration : 61, Loss : 0.930916252865338
Iteration : 71, Loss : 0.5062269920467352
Iteration : 81, Loss : 0.275283374511837
Iteration : 91, Loss : 0.14969754176132244
Iteration : 101, Loss : 0.08140467635984756
Iteration : 111, Loss : 0.044267402492267266
Iteration : 121, Loss : 0.02407236305135653
Iteration : 131, Loss : 0.013090414848206555
Iteration : 141, Loss : 0.0071184935410191314
Iteration : 151, Loss : 0.0038709965177668067
Iteration : 161, Loss : 0.0021050260078507234
Iteration : 171, Loss : 0.0011447012347829103
Iteration : 181, Loss : 0.0006224820558161947
Iteration : 191, Loss : 0.00033850222052625716
Final weights :  [-3.3990955  -0.20180899  0.80271349]
Final bias :  0.6009044964039992


In [43]:
#Coding backpropagation for a layer of neuron 

import numpy as np

inputs = np.array([1,2,3,4])

weights=np.array([[0.1,0.2,0.3,0.4],
                  [0.5,0.6,0.7,0.8],
                  [0.9,1.0,1.1,1.2]])

biases=np.array([0.1,0.2,0.3])

learning_rate=0.001

def ReLU(x):
    return np.maximum(0,x)

def derivative_relu(x):
    return np.where(x>0,1,0)

for i in range(200):
    #Doing one forward pass
    z=np.dot(weights,inputs)+biases
    a=ReLU(z)
    y=np.sum(a)

    loss=y**2

    #Backward pass

    dL_dY=2*y
    dY_da=np.ones_like(a)

    dL_da=dL_dY*dY_da
    da_dz=derivative_relu(z)
    
    dL_dz=dL_da*da_dz

    dL_dw=np.outer(dL_dz,inputs)
    dL_db=dL_dz

    weights-=learning_rate*dL_dw
    biases-=learning_rate*dL_db

    if i%10==0:
        print(f"Iteration : {i+1}, Loss : {loss}")

print("Final weights",weights)
print("Final biases",biases)


Iteration : 1, Loss : 466.56000000000006
Iteration : 11, Loss : 22.06563016367191
Iteration : 21, Loss : 5.32959636083938
Iteration : 31, Loss : 1.4816686310919343
Iteration : 41, Loss : 0.4119152340489983
Iteration : 51, Loss : 0.11451559173294888
Iteration : 61, Loss : 0.03183621207946751
Iteration : 71, Loss : 0.008850710931419982
Iteration : 81, Loss : 0.0024605654653895997
Iteration : 91, Loss : 0.0006840560556525436
Iteration : 101, Loss : 0.00019017282566014768
Iteration : 111, Loss : 5.286950290216462e-05
Iteration : 121, Loss : 1.4698126966450583e-05
Iteration : 131, Loss : 4.086191934160638e-06
Iteration : 141, Loss : 1.1359926717817246e-06
Iteration : 151, Loss : 3.1581466831074093e-07
Iteration : 161, Loss : 8.77988980016028e-08
Iteration : 171, Loss : 2.4408766481731806e-08
Iteration : 181, Loss : 6.785824135779993e-09
Iteration : 191, Loss : 1.8865111121823123e-09
Final weights [[-0.00698895 -0.01397789 -0.02096684 -0.02795579]
 [ 0.25975286  0.11950572 -0.02074143 -0.160