In [1]:
#Neuron with 3 inputs

inputs = [1,2,3]
weights = [0.2,0.8,-0.5]
bias=2

outputs=(inputs[0]*weights[0]+inputs[1]*weights[1]+inputs[2]*weights[2]+bias)
print(outputs)

2.3


In [2]:
#Neuron with 4 inputs

inputs = [1,2,3,2.5]
weights = [0.2,0.8,-0.5,1]
bias = 2

output=(inputs[0]*weights[0]+inputs[1]*weights[1]+inputs[2]*weights[2]+inputs[3]*weights[3]+bias)
print(output)

4.8


In [3]:
#Layer of Neurons

inputs=[1,2,3,2.5]

weights=[[0.2,0.8,-0.5,1],
         [0.5,-0.91,0.26,-0.5],
         [-0.26,-0.27,0.17,0.87]]

biases=[2,3,0.5]

weight1=weights[0]
weight2=weights[1]
weight3=weights[2]

outputs=(inputs[0]*weight1[0]+inputs[1]*weight1[1]+inputs[2]*weight1[2]+inputs[3]*weight1[3]+biases[0],
         inputs[0]*weight2[0]+inputs[1]*weight2[1]+inputs[2]*weight2[2]+inputs[3]*weight2[3]+biases[1],
         inputs[0]*weight3[0]+inputs[1]*weight3[1]+inputs[2]*weight3[2]+inputs[3]*weight3[3]+biases[2])
#Since inputs are same for the three neurons in a layer - it is the weights and biases that change

print(outputs)

(4.8, 1.21, 2.385)


In [4]:
#Layer of Neurons using Loops

inputs=[1,2,3,2.5]

weights=[[0.2,0.8,-0.5,1],
         [0.5,-0.91,0.26,-0.5],
         [-0.26,-0.27,0.17,0.87]]

biases=[2,3,0.5]

output_list=[]

for n_weights,n_bias in zip(weights,biases):
    n_output=0
    for n_input,weight in zip(inputs,n_weights):
        n_output+=n_input*weight
    n_output+=n_bias
    output_list.append(n_output)

print(output_list)

[4.8, 1.21, 2.385]


In [10]:
# inputs=[1,2,3,2.5]

# weights=[[0.2,0.8,-0.5,1],
#          [0.5,-0.91,0.26,-0.5],
#          [-0.26,-0.27,0.17,0.87]]

# biases=[2,3,0.5]

# print(list(zip(weights,biases)))

In [11]:
#print(list(zip(inputs,weights[0])))

In [12]:
#Neurons and Layers - Using Numpy

In [13]:
#Neuron with 3 inputs - Numpy

import numpy as np

inputs=[1,2,3]
weights=[0.2,0.8,-0.5]
bias = 2
outputs=np.dot(inputs,weights)+bias
print(outputs)

2.3


In [18]:
#Layer of neurons - Numpy

import numpy as np

inputs=[[1],[2],[3],[2.5]]

weights=[[0.2,0.8,-0.5,1],
         [0.5,-0.91,0.26,-0.5],
         [-0.26,-0.27,0.17,0.87]]

biases=[[2],[3],[0.5]]

outputs=np.dot(weights,inputs)+biases
print(outputs)
#Much more elegant than coding individually or even using loops

[[4.8  ]
 [1.21 ]
 [2.385]]


In [19]:
#Processing batches of inputs

import numpy as np

inputs=[[1,2,3,2.5],[2,5,-1,2],[-1.5,2.7,3.3,-0.8]]

weights=[[0.2,0.8,-0.5,1],
         [0.5,-0.91,0.26,-0.5],
         [-0.26,-0.27,0.17,0.87]]

biases=[2,3,0.5]

outputs=np.dot(inputs,np.array(weights).T)+biases
print(outputs)


[[ 4.8    1.21   2.385]
 [ 8.9   -1.81   0.2  ]
 [ 1.41   1.051  0.026]]


In [20]:
#Coding multiple layers and stacking them together

import numpy as np

inputs=[[1,2,3,2.5],[2,5,-1,2],[-1.5,2.7,3.3,-0.8]]

weights1=[[0.2,0.8,-0.5,1],
         [0.5,-0.91,0.26,-0.5],
         [-0.26,-0.27,0.17,0.87]]

biases1=[2,3,0.5]

weights2=[[0.1,-0.14,0.5],
          [-0.5,0.12,-0.33],
          [-0.44,0.73,-0.13]]

biases2=[-1,2,-0.5]

arr_inputs=np.array(inputs)
arr_weights1=np.array(weights1)
arr_biases1=np.array(biases1)
arr_weights2=np.array(weights2)
arr_biases2=np.array(biases2)

outputs1=np.dot(arr_inputs,arr_weights1.T)+arr_biases1
outputs2=np.dot(outputs1,arr_weights2.T)+arr_biases2
print(outputs2)



[[ 0.5031  -1.04185 -2.03875]
 [ 0.2434  -2.7332  -5.7633 ]
 [-0.99314  1.41254 -0.35655]]


In [12]:
import numpy as np
class Activation_ReLU:
    def forward(self,inputs):
        self.outputs=np.maximum(0,inputs)
        return self.outputs

In [13]:
inputs=[0,2,-1,3.3,-2.7,1.1,2.2,-100]
relu=Activation_ReLU()
print(relu.forward(inputs))

[0.  2.  0.  3.3 0.  1.1 2.2 0. ]


In [21]:
softmax_outputs = np.array([[0.7,0.1,0.2],
                             [0.1,0.5,0.4],
                             [0.02,0.9,0.08]])
class_targets = [0,1,1]

relevant_values = softmax_outputs[range(len(softmax_outputs)),class_targets]
neg_log= (-np.log(relevant_values))
average_loss=np.mean(neg_log)
print(average_loss)

0.38506088005216804


In [22]:
y_pred=np.array([[0.7,0.1,0.2],
                  [0.1,0.5,0.4],
                  [0.02,0.9,0.08]])

y_true=np.array([[1,0,0],
                  [0,1,0],
                  [0,1,0]])

relevant_values=np.sum(y_pred*y_true,axis=1)
neg_loss= (-np.log(relevant_values))
average_loss=np.mean(neg_loss)
print(average_loss)

0.38506088005216804
